#!/bin/sh
# This script was created by make-mzscheme-launcher

# {{{ bindir
bindir="/usr/bin"
# }}} bindir

exec "${bindir}/racket" -N "$0" '-I' 'scheme/init' '-qt-' '/home/nilesh/Desktop/20th april/board-idea-change.scm'  ${1+"$@"}
